### ISSUE TITLE
nested requests in race condition problem

### ISSUE THREAD

**Issue by daniil00t** [Ssergeymiss/3-D-DASV#1]
Ёпта, пишу здесь ибо негде больше не придумал

**Comment by daniil00t** [comment]
Ну чо ты молчишь то емае

**Comment by Ssergeymiss** [comment]
Я позвоню завтра

Чт, 1 июня 2023 г. в 18:21, Daniil Shenyagin ***@***.***>:

**Comment by daniil00t** [comment]
Окей жду

**Comment by Ssergeymiss** [comment]
Бля, Дань, это пиздец
Я уже не вывожу
Позвоню как возможность появится

**Comment by Ssergeymiss** [comment]
Вы сильно обиделись что я не пришел?

**Comment by daniil00t** [comment]
все ок
